### ISSUE TITLE
Polymer 2 application template doesn't render in Opera

### ISSUE THREAD

**Issue by mattpalermo** [Polymer/polymer-cli#654]
### Description

Polymer 2 application template doesn't render in Opera.

### Versions & Environment

- Polymer CLI: 0.18.0-pre.15
- node: v6.10.2
- Operating System: Windows 10

#### Steps to Reproduce

1. Create a polymer 2 application project using `polymer init`
2. Serve the application using `polymer serve`
3. Navigate to the application using Opera

#### Expected Results

I expect that a header saying "Hello test-poly-app" is shown on the screen. This is shown when using the Chrome browser.

#### Actual Results

Nothing is shown on the screen and the console shows the following errors:
![capture](https://cloud.githubusercontent.com/assets/16647352/24950877/d401baca-1fb5-11e7-8661-b50fb00b00d9.PNG)

**Comment by justinfagnani** [comment]
This is almost certainly because we don't recognize the Opera UA string.

**Comment by justinfagnani** [comment]
@mattpalermo we have a workaround and two fixes for this. The workaround is to use `polymer serve --compile=never` for Opera. Fix #1 is for us to always patch in the `custom-elements-es5-adapter.js` file when compiling in polyserve, and fix #2 is to recognize the Opera UA.

**Comment by justinfagnani** [comment]
And, we had a PR already for fix 2, which I just merged: https://github.com/Polymer/polyserve/pull/175

**Comment by rictic** [comment]
This will also be helped by https://github.com/Polymer/polymer-cli/pull/635

**Comment by mattpalermo** [comment]
Thankyou everyone. So the user agent is used to determine which polyfills need to be applied? This seems so fragile. Is there no other way?

**Comment by rictic** [comment]
With #635 the default will be an app that works in all browsers and only if we have positive evidence from the user agent that the browser can take ES6 will we give them ES6

**Comment by JGSolutions** [comment]
Still happening for me:

polymer-cli: 1.5.6
nodejs: 6.11.2
macOS
